import type { Task } from '@/types'

// Same project ids/names used in mockContractData.ts / ProjectsPage.tsx mock data
export interface MockTaskProject {
  id: string
  name: string
}

export const mockTaskProjects: MockTaskProject[] = [
  { id: '1', name: 'Villa Knokke' },
  { id: '2', name: 'Kantoorgebouw Hasselt' },
  { id: '3', name: 'Appartement Gent' },
  { id: '4', name: 'Woning Leuven' },
  { id: '5', name: 'Residentie Brugge' },
  { id: '6', name: 'Magazijn Antwerpen' },
]

export function getTaskProjectById(id: string | null): MockTaskProject | undefined {
  return mockTaskProjects.find((p) => p.id === id)
}

export interface MockAssignee {
  id: string
  name: string
  initials: string
  color: string
}

// Same manager names/colors used in ProjectsPage.tsx mock data
export const mockAssignees: MockAssignee[] = [
  { id: 'u1', name: 'Jan Peeters', initials: 'JP', color: 'bg-blue-500' },
  { id: 'u2', name: 'Sarah Claes', initials: 'SC', color: 'bg-purple-500' },
  { id: 'u3', name: 'Tom Martens', initials: 'TM', color: 'bg-emerald-500' },
  { id: 'u4', name: 'Pieter VDB', initials: 'PV', color: 'bg-amber-500' },
  { id: 'u5', name: 'Lisa Bogaert', initials: 'LB', color: 'bg-rose-500' },
]

export function getAssigneeById(id: string | null): MockAssignee | undefined {
  return mockAssignees.find((a) => a.id === id)
}

// Mock tasks — would come from the `tasks` table in a real backend.
// Dates are relative to "today" so overdue/today/this-week buckets stay realistic.
const today = new Date()
function daysFromNow(days: number): string {
  const d = new Date(today)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export const mockTasks: Task[] = [
  {
    id: 't1',
    company_id: 'c1',
    project_id: '1',
    title: 'Funderingen uitgraven',
    description: 'Uitgraving en stabilisatie van de funderingssleuven volgens plan.',
    status: 'done',
    priority: 'high',
    assignee_id: 'u1',
    due_date: daysFromNow(-12),
    completed_at: daysFromNow(-10),
    estimated_hours: 24,
    actual_hours: 26,
    tags: ['ruwbouw'],
    created_by: 'u1',
    created_at: daysFromNow(-20),
    updated_at: daysFromNow(-10),
  },
  {
    id: 't2',
    company_id: 'c1',
    project_id: '1',
    title: 'Eindcontrole sanitair',
    description: 'Controle van alle sanitaire aansluitingen vóór oplevering.',
    status: 'in_progress',
    priority: 'urgent',
    assignee_id: 'u1',
    due_date: daysFromNow(-1),
    completed_at: null,
    estimated_hours: 6,
    actual_hours: 2,
    tags: ['urgent', 'veiligheid'],
    created_by: 'u1',
    created_at: daysFromNow(-5),
    updated_at: daysFromNow(-1),
  },
  {
    id: 't3',
    company_id: 'c1',
    project_id: '1',
    title: 'Oplevering villa voorbereiden',
    description: 'Checklist opstellen en afspraak inplannen met de klant.',
    status: 'todo',
    priority: 'high',
    assignee_id: 'u5',
    due_date: daysFromNow(3),
    completed_at: null,
    estimated_hours: 4,
    actual_hours: null,
    tags: [],
    created_by: 'u1',
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-2),
  },
  {
    id: 't4',
    company_id: 'c1',
    project_id: '2',
    title: 'Elektrische bekabeling 1e verdieping',
    description: 'Volledige bekabeling volgens elektrisch schema leggen.',
    status: 'in_progress',
    priority: 'medium',
    assignee_id: 'u2',
    due_date: daysFromNow(2),
    completed_at: null,
    estimated_hours: 40,
    actual_hours: 18,
    tags: ['technieken'],
    created_by: 'u2',
    created_at: daysFromNow(-8),
    updated_at: daysFromNow(-1),
  },
  {
    id: 't5',
    company_id: 'c1',
    project_id: '2',
    title: 'HVAC-inspectie plannen',
    description: 'Externe inspecteur contacteren voor keuring HVAC-installatie.',
    status: 'review',
    priority: 'medium',
    assignee_id: 'u2',
    due_date: daysFromNow(0),
    completed_at: null,
    estimated_hours: 2,
    actual_hours: 2,
    tags: [],
    created_by: 'u2',
    created_at: daysFromNow(-6),
    updated_at: daysFromNow(0),
  },
  {
    id: 't6',
    company_id: 'c1',
    project_id: '2',
    title: 'Bestelling liftinstallatie opvolgen',
    description: 'Leveringsdatum bevestigen bij leverancier.',
    status: 'todo',
    priority: 'low',
    assignee_id: 'u4',
    due_date: daysFromNow(10),
    completed_at: null,
    estimated_hours: 1,
    actual_hours: null,
    tags: ['materiaal'],
    created_by: 'u2',
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-3),
  },
  {
    id: 't7',
    company_id: 'c1',
    project_id: '3',
    title: 'Betonstort fase 2',
    description: 'Stort van de vloerplaat tweede verdieping.',
    status: 'done',
    priority: 'high',
    assignee_id: 'u3',
    due_date: daysFromNow(-6),
    completed_at: daysFromNow(-6),
    estimated_hours: 16,
    actual_hours: 15,
    tags: ['ruwbouw'],
    created_by: 'u3',
    created_at: daysFromNow(-14),
    updated_at: daysFromNow(-6),
  },
  {
    id: 't8',
    company_id: 'c1',
    project_id: '3',
    title: 'Raamprofielen plaatsen',
    description: 'Plaatsing van de aluminium raamprofielen op alle verdiepingen.',
    status: 'todo',
    priority: 'medium',
    assignee_id: 'u3',
    due_date: null,
    completed_at: null,
    estimated_hours: 20,
    actual_hours: null,
    tags: [],
    created_by: 'u3',
    created_at: daysFromNow(-4),
    updated_at: daysFromNow(-4),
  },
  {
    id: 't9',
    company_id: 'c1',
    project_id: '3',
    title: 'Asbestinventaris opvragen',
    description: 'Verplichte asbestinventaris aanvragen vóór sloopwerken.',
    status: 'cancelled',
    priority: 'low',
    assignee_id: 'u3',
    due_date: daysFromNow(-15),
    completed_at: null,
    estimated_hours: 1,
    actual_hours: null,
    tags: [],
    created_by: 'u3',
    created_at: daysFromNow(-25),
    updated_at: daysFromNow(-15),
  },
  {
    id: 't10',
    company_id: 'c1',
    project_id: '4',
    title: 'Bestelling dakpannen plaatsen',
    description: 'Order doorgeven aan leverancier voor de leien dakbedekking.',
    status: 'todo',
    priority: 'urgent',
    assignee_id: 'u4',
    due_date: daysFromNow(-2),
    completed_at: null,
    estimated_hours: 1,
    actual_hours: null,
    tags: ['urgent', 'materiaal'],
    created_by: 'u4',
    created_at: daysFromNow(-7),
    updated_at: daysFromNow(-7),
  },
  {
    id: 't11',
    company_id: 'c1',
    project_id: '4',
    title: 'Isolatie spouwmuur controleren',
    description: 'Controle of de spouwisolatie correct is aangebracht.',
    status: 'review',
    priority: 'medium',
    assignee_id: 'u4',
    due_date: daysFromNow(1),
    completed_at: null,
    estimated_hours: 3,
    actual_hours: 3,
    tags: [],
    created_by: 'u4',
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(0),
  },
  {
    id: 't12',
    company_id: 'c1',
    project_id: '5',
    title: 'Gevelreiniging na oplevering',
    description: 'Gevels reinigen van bouwvuil en cementresten.',
    status: 'done',
    priority: 'low',
    assignee_id: 'u5',
    due_date: daysFromNow(-20),
    completed_at: daysFromNow(-19),
    estimated_hours: 8,
    actual_hours: 7,
    tags: [],
    created_by: 'u5',
    created_at: daysFromNow(-30),
    updated_at: daysFromNow(-19),
  },
  {
    id: 't13',
    company_id: 'c1',
    project_id: '5',
    title: 'Eindafrekening opmaken',
    description: 'Eindafrekening en meerwerken verzamelen voor facturatie.',
    status: 'in_progress',
    priority: 'high',
    assignee_id: 'u5',
    due_date: daysFromNow(4),
    completed_at: null,
    estimated_hours: 5,
    actual_hours: 1,
    tags: ['administratie'],
    created_by: 'u5',
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-1),
  },
  {
    id: 't14',
    company_id: 'c1',
    project_id: '6',
    title: 'Vloerplaat magazijn afwerken',
    description: 'Industriële vloercoating aanbrengen in volledige hal.',
    status: 'todo',
    priority: 'medium',
    assignee_id: 'u1',
    due_date: daysFromNow(14),
    completed_at: null,
    estimated_hours: 30,
    actual_hours: null,
    tags: [],
    created_by: 'u1',
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
  {
    id: 't15',
    company_id: 'c1',
    project_id: '6',
    title: 'Brandveiligheidskeuring aanvragen',
    description: 'Keuring aanvragen bij erkende instantie vóór ingebruikname.',
    status: 'todo',
    priority: 'urgent',
    assignee_id: 'u1',
    due_date: daysFromNow(0),
    completed_at: null,
    estimated_hours: 2,
    actual_hours: null,
    tags: ['urgent', 'veiligheid'],
    created_by: 'u1',
    created_at: daysFromNow(-6),
    updated_at: daysFromNow(-6),
  },
  {
    id: 't16',
    company_id: 'c1',
    project_id: '2',
    title: 'Werfvergadering voorbereiden',
    description: 'Agenda en voortgangsrapport opstellen voor wekelijkse werfvergadering.',
    status: 'todo',
    priority: 'low',
    assignee_id: 'u2',
    due_date: daysFromNow(5),
    completed_at: null,
    estimated_hours: 1,
    actual_hours: null,
    tags: [],
    created_by: 'u2',
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
]
